services:
  - type: web
    name: lawyer-frontend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    repo: https://github.com/yooosef3/MERN_Lawyer-Appointment_FrontEnd.git
    branch: main
    autoDeploy: true
    healthCheckPath: /
